Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -88,15 +88,18 @@ jobs:
 
           # Check if requirements.txt is present in the root directory
           if [ ! -f "requirements.txt" ]; then
-            echo "requirements.txt not found in the repository root. Please check your repo structure."
-            exit 1
+          echo "requirements.txt not found in the repository root. Please check your repo structure."
+          exit 1
           fi
+
+          # Set permissions on the /opt/odoo18 directory to ensure the user can access it
+          sudo chown -R odoo18:odoo18 /opt/odoo18
 
           # Set up virtual environment if it doesn't exist
           if [ ! -d "/opt/odoo18/venv" ]; then
-            sudo python3 -m venv /opt/odoo18/venv
-            sudo chown -R odoo18:odoo18 /opt/odoo18/venv  # Ensure proper ownership
-            echo "Virtual environment created."
+          sudo python3 -m venv /opt/odoo18/venv
+          sudo chown -R odoo18:odoo18 /opt/odoo18/venv  # Ensure proper ownership
+          echo "Virtual environment created."
           fi
 
           # Fix permissions for the virtual environment
